{
 "title": "Observability Hub Resources",
 "description": "Information about the resources consumption in the HUB because of observability.",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "thanos_receive_storage_limit", "label": "storage", "query": "25" },
   { "name": "thanos_compact_storage_limit", "label": "storage", "query": "100" },
   { "name": "thanos_rule_storage_limit", "label": "storage", "query": "10" },
   { "name": "thanos_store_storage_limit", "label": "storage", "query": "25" },
   { "name": "step", "query": "24h" }
  ]
 },
 "panels": [
  { "title": "Clusters and Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of spoke clusters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(group by (cluster) (up{apiserver=\"kube-apiserver\"}))",
     "legendFormat": "spokes"
    }
   ]
  },
  { "title": "Different metrics", "type": "timeseries", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 } },
  { "title": "Storage Historical Consumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Storage for 'thanos-receive'",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{cluster=\"local-cluster\",namespace=\"open-cluster-management-observability\",persistentvolumeclaim=~'data-observability-thanos-receive-default.*'}/1024/1024",
     "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
    }
   ]
  },
  {
   "title": "Storage for 'thanos-store'",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{cluster=\"local-cluster\",namespace=\"open-cluster-management-observability\",persistentvolumeclaim=~'data-observability-thanos-store-shard.*'}/1024/1024",
     "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
    }
   ]
  },
  {
   "title": "Storage for 'thanos-compact'",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{cluster=\"local-cluster\",namespace=\"open-cluster-management-observability\",persistentvolumeclaim=~'data-observability-thanos-compact.*'}/1024/1024",
     "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
    }
   ]
  },
  {
   "title": "Storage for 'thanos-rule'",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{cluster=\"local-cluster\",namespace=\"open-cluster-management-observability\",persistentvolumeclaim=~'data-observability-thanos-rule.*'}/1024/1024",
     "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
    }
   ]
  },
  { "title": "Storage Current Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Persistent Volume Claim",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{namespace=\"open-cluster-management-observability\"}/1024/1024/1024)"
    },
    {
     "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes{namespace=\"open-cluster-management-observability\"}/1024/1024/1024)"
    },
    {
     "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_available_bytes{namespace=\"open-cluster-management-observability\"}/1024/1024/1024)"
    },
    {
     "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes{namespace=\"open-cluster-management-observability\"}/kubelet_volume_stats_capacity_bytes{namespace=\"open-cluster-management-observability\"} * 100)"
    }
   ]
  },
  { "title": "Resources Consumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "CPU Consumption",
   "type": "timeseries",
   "description": "Only on the Namespaces that would be affected about the number of spokes and different metrics.",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "sum by (namespace) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster='local-cluster',namespace=~'open-cluster-management|open-cluster-management-hub|open-cluster-management-observability'})",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory Consumption (GB)",
   "type": "timeseries",
   "description": "Only on the Namespaces that would be affected about the number of spokes and different metrics.",
   "gridPos": { "h": 16, "w": 11, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster='local-cluster',container!='',namespace='open-cluster-management'})/1024/1024/1024",
     "legendFormat": "open-cluster-management"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{cluster='local-cluster',container!='',namespace='open-cluster-management-hub'})/1024/1024/1024",
     "legendFormat": "open-cluster-management-hub"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{cluster='local-cluster',container!='',namespace='open-cluster-management-observability'})/1024/1024/1024",
     "legendFormat": "open-cluster-management-observability"
    }
   ]
  },
  {
   "title": "Current Rate of Bytes Received",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(instance:node_network_receive_bytes_excluding_lo:rate1m{cluster=\"local-cluster\"})",
     "legendFormat": "received"
    }
   ]
  },
  {
   "title": "Current Rate of Bytes Transmitted",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(instance:node_network_transmit_bytes_excluding_lo:rate1m{cluster=\"local-cluster\"})   ",
     "legendFormat": "transmited"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } }
 ]
}